import type { ContentItem, ContentType } from './types'

export const contentTypeLabels: Record<ContentType, string> = {
  article: '文章',
  tool: 'AI 工具',
  podcast: '播客感悟',
  project: '项目',
  resource: '资源',
}

export const content: ContentItem[] = [
  {
    slug: 'my-first-week-with-ai',
    type: 'article',
    title: '我开始认真使用 AI 的第一周',
    eyebrow: '示例内容 · 学习记录',
    summary: '没有宏大的路线，先从每天真正遇到的问题开始，记录 AI 帮到我和没有帮到我的地方。',
    category: 'AI 学习记录',
    tags: ['AI 入门', '学习记录'],
    date: '2026-07-12',
    readTime: '5 分钟',
    featured: true,
    body: [
      '这是一篇用于展示页面结构的示例文章，正式上线后会由 Flora 的真实学习记录替换。',
      '我没有先给自己制定一条看起来很完美的学习路线，而是从生活中真正遇到的问题开始：整理资料、理解陌生概念，以及把模糊的想法变成可以行动的步骤。',
      'AI 最有帮助的时刻，并不是直接给我一个答案，而是让我更容易继续问下去。接下来，我会把这些真实体验持续记录下来。',
    ],
  },
  {
    slug: 'small-efficiency-habits',
    type: 'article',
    title: '让学习轻松一点的三个小习惯',
    eyebrow: '示例内容 · 效率学习',
    summary: '比起追求复杂的系统，我更愿意保留几个能够每天重复的小动作。',
    category: '效率学习',
    tags: ['效率', '自我提升'],
    date: '2026-07-10',
    readTime: '4 分钟',
    body: [
      '这是一篇示例内容，用来预览文章列表、详情页和搜索结果的展示效果。',
      '真正能够长期保持的学习方法，通常都足够简单。每天只记录一个问题、只整理一次收件箱、只为明天留下一个明确的开始点，也会慢慢形成稳定的节奏。',
    ],
  },
  {
    slug: 'chatgpt-learning-companion',
    type: 'tool',
    title: '把 AI 对话工具当作学习搭档',
    eyebrow: '示例内容 · AI 对话',
    summary: '它更适合陪你拆解问题、补充视角，而不是替你完成所有思考。',
    category: 'AI 对话',
    tags: ['AI 对话', '学习'],
    date: '2026-07-11',
    readTime: '6 分钟',
    featured: true,
    rating: 5,
    suitableFor: '刚开始接触 AI、希望辅助学习与整理思路的人',
    body: [
      '这是一个 AI 工具详情页示例，评价与教程会在 Flora 实际体验后更新。',
      '使用体感：对话工具最明显的价值，是在你卡住时提供新的提问角度。它可以解释术语、生成练习，也可以帮你检查自己是否真的理解了某个概念。',
      '使用建议：先写下自己的理解，再让 AI 指出遗漏；要求它用例子解释；最后用自己的话重新总结。这样更容易把工具变成学习搭档。',
    ],
  },
  {
    slug: 'ai-weekly-review',
    type: 'tool',
    title: '用 AI 做一次温和的每周复盘',
    eyebrow: '示例内容 · 自我提升',
    summary: '不追求数据化自己，只用几个问题看见这一周真正发生了什么。',
    category: 'AI 用于自我提升的探索',
    tags: ['复盘', '自我提升'],
    date: '2026-07-09',
    readTime: '5 分钟',
    rating: 4,
    suitableFor: '想要建立复盘习惯，但不喜欢复杂模板的人',
    body: [
      '这是一篇示例工具实践，正式内容将补充完整的提问模板和 Flora 的使用体验。',
      '把一周的零散记录交给 AI 之前，先删除隐私信息。可以让它帮助归纳反复出现的问题，但最终如何评价这一周，仍由自己决定。',
    ],
  },
  {
    slug: 'a-podcast-about-starting',
    type: 'podcast',
    title: '先开始，再慢慢找到自己的方向',
    eyebrow: '示例内容 · 播客感悟',
    summary: '听完一期关于长期创作的播客，我重新理解了“还没准备好”这句话。',
    category: '播客感悟',
    tags: ['创作', '成长'],
    date: '2026-07-08',
    readTime: '3 分钟',
    featured: true,
    body: [
      '这是用于展示播客感悟页面的示例内容，不代表对某个真实节目的引用或转述。',
      '我记住的不是某条技巧，而是一个很简单的想法：方向不一定是在出发前想清楚的，也可能是在持续行动后慢慢浮现。Help Myself 也会从这样的状态开始。',
    ],
  },
  {
    slug: 'help-myself-project',
    type: 'project',
    title: 'Help Myself：我的个人 AI 学习空间',
    eyebrow: '进行中 · 个人项目',
    summary: '从一句“我想做一个博客”开始，把内容、审美和真实的学习过程放进同一个空间。',
    category: '网站项目',
    tags: ['个人网站', '产品设计'],
    date: '2026-07-12',
    readTime: '7 分钟',
    featured: true,
    body: [
      'Help Myself 是 Flora 的第一个长期个人网站项目。它面向对 AI 感兴趣的同学，分享真实体验、教程、播客感悟与项目过程。',
      '项目目前完成了定位、信息架构、品牌角色和第一版前端体验。后续会继续接入可视化后台，并把示例内容逐步替换成真实记录。',
      '遇到的问题：如何在沉浸式视觉和内容可读性之间取得平衡。当前方案只在首页使用明显的空间转场，进入文章后恢复安静、清晰的阅读界面。',
    ],
  },
]

export const navItems = [
  { label: '首页', to: '/' },
  { label: '文章', to: '/articles' },
  { label: 'AI 工具', to: '/tools' },
  { label: '播客感悟', to: '/podcasts' },
  { label: '项目', to: '/projects' },
  { label: '资源库', to: '/resources' },
  { label: '关于 Flora', to: '/about' },
]
