create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;
revoke all on table public.admin_users from anon, authenticated;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

create table if not exists public.contents (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  type text not null check (type in ('article', 'tool', 'podcast', 'project', 'resource')),
  title text not null check (char_length(title) between 2 and 120),
  eyebrow text not null default '',
  summary text not null default '',
  category text not null default '',
  tags text[] not null default '{}',
  published_date date not null default current_date,
  read_time text not null default '',
  featured boolean not null default false,
  rating smallint check (rating between 1 and 5),
  suitable_for text,
  external_url text,
  cover_image text,
  body text[] not null default '{}',
  status text not null default 'draft' check (status in ('draft', 'published')),
  pinned boolean not null default false,
  is_sample boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contents_public_order_idx
  on public.contents (status, pinned desc, published_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists contents_set_updated_at on public.contents;
create trigger contents_set_updated_at
before update on public.contents
for each row execute function public.set_updated_at();

alter table public.contents enable row level security;

grant select on public.contents to anon, authenticated;
grant insert, update, delete on public.contents to authenticated;
grant usage, select on sequence public.contents_id_seq to authenticated;

drop policy if exists "Published content is public" on public.contents;
create policy "Published content is public"
on public.contents for select
to anon, authenticated
using (status = 'published');

drop policy if exists "Admins can read all content" on public.contents;
create policy "Admins can read all content"
on public.contents for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can create content" on public.contents;
create policy "Admins can create content"
on public.contents for insert
to authenticated
with check (public.is_admin());

drop policy if exists "Admins can update content" on public.contents;
create policy "Admins can update content"
on public.contents for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can delete content" on public.contents;
create policy "Admins can delete content"
on public.contents for delete
to authenticated
using (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'content-images',
  'content-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins can view uploaded images" on storage.objects;
create policy "Admins can view uploaded images"
on storage.objects for select
to authenticated
using (bucket_id = 'content-images' and public.is_admin());

drop policy if exists "Admins can upload images" on storage.objects;
create policy "Admins can upload images"
on storage.objects for insert
to authenticated
with check (bucket_id = 'content-images' and public.is_admin());

drop policy if exists "Admins can update images" on storage.objects;
create policy "Admins can update images"
on storage.objects for update
to authenticated
using (bucket_id = 'content-images' and public.is_admin())
with check (bucket_id = 'content-images' and public.is_admin());

drop policy if exists "Admins can delete images" on storage.objects;
create policy "Admins can delete images"
on storage.objects for delete
to authenticated
using (bucket_id = 'content-images' and public.is_admin());

insert into public.contents (
  slug, type, title, eyebrow, summary, category, tags, published_date,
  read_time, featured, rating, suitable_for, body, status, pinned, is_sample
) values
(
  'my-first-week-with-ai', 'article', '我开始认真使用 AI 的第一周', '示例内容 · 学习记录',
  '没有宏大的路线，先从每天真正遇到的问题开始，记录 AI 帮到我和没有帮到我的地方。',
  'AI 学习记录', array['AI 入门', '学习记录'], '2026-07-12', '5 分钟', true, null, null,
  array['这是一篇用于展示页面结构的示例文章，正式上线后会由 Flora 的真实学习记录替换。', '我没有先给自己制定一条看起来很完美的学习路线，而是从生活中真正遇到的问题开始。', 'AI 最有帮助的时刻，并不是直接给我一个答案，而是让我更容易继续问下去。'],
  'published', true, true
),
(
  'small-efficiency-habits', 'article', '让学习轻松一点的三个小习惯', '示例内容 · 效率学习',
  '比起追求复杂的系统，我更愿意保留几个能够每天重复的小动作。',
  '效率学习', array['效率', '自我提升'], '2026-07-10', '4 分钟', false, null, null,
  array['这是一篇示例内容，用来预览文章列表、详情页和搜索结果的展示效果。', '真正能够长期保持的学习方法，通常都足够简单。'],
  'published', false, true
),
(
  'chatgpt-learning-companion', 'tool', '把 AI 对话工具当作学习搭档', '示例内容 · AI 对话',
  '它更适合陪你拆解问题、补充视角，而不是替你完成所有思考。',
  'AI 对话', array['AI 对话', '学习'], '2026-07-11', '6 分钟', true, 5,
  '刚开始接触 AI、希望辅助学习与整理思路的人',
  array['这是一个 AI 工具详情页示例，评价与教程会在 Flora 实际体验后更新。', '对话工具最明显的价值，是在你卡住时提供新的提问角度。', '先写下自己的理解，再让 AI 指出遗漏，最后用自己的话重新总结。'],
  'published', true, true
),
(
  'ai-weekly-review', 'tool', '用 AI 做一次温和的每周复盘', '示例内容 · 自我提升',
  '不追求数据化自己，只用几个问题看见这一周真正发生了什么。',
  'AI 用于自我提升的探索', array['复盘', '自我提升'], '2026-07-09', '5 分钟', false, 4,
  '想要建立复盘习惯，但不喜欢复杂模板的人',
  array['这是一篇示例工具实践，正式内容将补充完整的提问模板和 Flora 的使用体验。', '把一周的零散记录交给 AI 之前，先删除隐私信息。'],
  'published', false, true
),
(
  'a-podcast-about-starting', 'podcast', '先开始，再慢慢找到自己的方向', '示例内容 · 播客感悟',
  '听完一期关于长期创作的播客，我重新理解了“还没准备好”这句话。',
  '播客感悟', array['创作', '成长'], '2026-07-08', '3 分钟', true, null, null,
  array['这是用于展示播客感悟页面的示例内容，不代表对某个真实节目的引用或转述。', '方向不一定是在出发前想清楚的，也可能是在持续行动后慢慢浮现。'],
  'published', true, true
),
(
  'help-myself-project', 'project', 'Help Myself：我的个人 AI 学习空间', '进行中 · 个人项目',
  '从一句“我想做一个博客”开始，把内容、审美和真实的学习过程放进同一个空间。',
  '网站项目', array['个人网站', '产品设计'], '2026-07-12', '7 分钟', true, null, null,
  array['Help Myself 是 Flora 的第一个长期个人网站项目。', '项目目前完成了定位、信息架构、品牌角色和第一版前端体验。', '当前方案只在首页使用明显的空间转场，进入文章后恢复安静、清晰的阅读界面。'],
  'published', true, true
)
on conflict (slug) do nothing;
